### PR TITLE
Updates ember cli

### PR DESCRIPTION
**Pull request by jbailey4**
Additionally updates the EmberApp#javascript method to work with the new handling of vendor/addon modules. Particularly the change of moving the loader.js dep from a bower component to a node module, which was not getting loaded with newer versions of ember-cli.

This is related to https://github.com/duizendnegen/ember-cli-lazy-load/issues/11

### CODE REVIEW

**Comment by duizendnegen** [comment]
Is this ready to merge? Which versions of ember-cli is this known to support?

**Comment by jbailey4** [comment]
Yes this is ready to merge. The ember-cli version should be a version >= 2.3.0

**Comment by duizendnegen** [comment]
:+1: thanks, now available on npm as `0.3.0`.

**Comment by jbailey4** [comment]
Awesome thank you 😄

**Pull request merged**
